// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Client._Lua.Styles;
using Content.Client.Stylesheets;
using Content.Shared._Lua.Starmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class PayoutCollectorWindow : LunaWindow
{
    public event Action? OnClaim;

    public PayoutCollectorWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyLunaChrome();
        ApplyLunaInterior();
        ClaimButton.OnPressed += _ => OnClaim?.Invoke();
    }

    private void ApplyLunaInterior()
    {
        Shell.PanelOverride = LunaWindowStyle.Shell();
        LunaWindowStyle.StyleDivider(Divider);
        LunaWindowStyle.StyleHeading(FactionLabel);
        LunaWindowStyle.StyleValue(OwnedLabel);
        LunaWindowStyle.StyleValue(AccumLabel);
        LunaWindowStyle.StyleSecondary(RateLabel);
        LunaWindowStyle.StyleHeading(HistoryHeadingLabel);
        LunaWindowStyle.StyleMuted(HistoryEmptyLabel);
        ClaimButton.AddStyleClass(StyleNano.StyleClassButtonNavCompact);
        if (ClaimButton.Label != null)
        {
            ClaimButton.Label.FontOverride = LunaWindowStyle.FontSmall;
            ClaimButton.Label.FontColorOverride = LunaWindowStyle.AccentGood;
        }
    }

    public void Update(PayoutCollectorBuiState state)
    {
        var factionKey = $"payout-faction-{state.Faction}";
        var factionName = Loc.TryGetString(factionKey, out var localizedFaction)
            ? localizedFaction
            : state.Faction;

        FactionLabel.Text = Loc.GetString("payout-faction", ("faction", factionName));
        OwnedLabel.Text = Loc.GetString("payout-owned", ("count", state.OwnedStations));
        AccumLabel.Text = Loc.GetString("payout-accum", ("amount", state.Accumulated));
        RateLabel.Text = Loc.GetString("payout-rate",
            ("amount", state.PayoutPerStation),
            ("interval", FormatInterval(state.IntervalSeconds)));

        HistoryContainer.RemoveAllChildren();
        var history = state.ClaimHistory ?? new List<PayoutClaimHistoryEntry>();
        var hasHistory = history.Count > 0;
        HistoryEmptyLabel.Visible = !hasHistory;
        HistoryContainer.Visible = hasHistory;

        if (hasHistory)
        {
            foreach (var entry in history)
            {
                var row = new Label
                {
                    Text = Loc.GetString("payout-history-entry",
                        ("name", entry.CharacterName),
                        ("amount", entry.Amount)),
                };
                LunaWindowStyle.StyleSecondary(row);
                HistoryContainer.AddChild(row);
            }
        }

        ClaimButton.Disabled = state.Accumulated <= 0;
    }

    private static string FormatInterval(int seconds)
    {
        if (seconds >= 3600 && seconds % 3600 == 0)
        {
            var hours = seconds / 3600;
            return hours == 1
                ? Loc.GetString("payout-interval-hour")
                : Loc.GetString("payout-interval-hours", ("hours", hours));
        }

        if (seconds >= 60 && seconds % 60 == 0)
            return Loc.GetString("payout-interval-minutes", ("minutes", seconds / 60));

        return Loc.GetString("payout-interval-seconds", ("seconds", seconds));
    }
}
