using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Expedition;
using Content.Shared._Lua.Starmap;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using System.Numerics;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private ShuttleConsoleMode _mode = ShuttleConsoleMode.Nav;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;
    public event Action<NetEntity?, NetEntity>? RequestTrackEntity; // Frontier
    public event Action<Star>? OnWarpToStarRequest;
    public event Action<MapCoordinates, Angle>? RequestAutopilot; // Mono


    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;
    public event Action<List<NetEntity>>? UndockAllRequest;
    public event Action<List<NetEntity>, bool>? ToggleFTLLockRequest;
    public event Action<bool>? OnStarMapVisibilityChanged;
    public event Action<bool>? OnMapVisibilityChanged;
    public event Action<bool>? OnExpVisibilityChanged;
    public event Action? OnWeaponSelectionChanged; // Lua
    public event Action? OnFireControlRefresh; // Lua
    public event Action<ushort, int>? OnClaimExpedition;
    public event Action? OnConfirmExpedition;
    public event Action? OnCancelExpedition;
    public event Action? OnFinishExpedition;

    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Mode switching
        NavModeButton.OnPressed += NavPressed;
        MapModeButton.OnPressed += MapPressed;
        StarMapModeButton.OnPressed += StarMapPressed; // Lua StarMap
        DockModeButton.OnPressed += DockPressed;
        ExpModeButton.OnPressed += ExpPressed;

        // Modes are exclusive
        var group = new ButtonGroup();

        NavModeButton.Group = group;
        MapModeButton.Group = group;
        StarMapModeButton.Group = group; // Lua StarMap
        DockModeButton.Group = group;
        ExpModeButton.Group = group;

        NavModeButton.Pressed = true;
        SetupMode(_mode);

        MapContainer.RequestFTL += (coords, angle) =>
        {
            RequestFTL?.Invoke(coords, angle);
        };

        MapContainer.RequestAutopilot += (coords, angle) =>
        {
            RequestAutopilot?.Invoke(coords, angle);
        };

        MapContainer.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        // Frontier: entity tracking
        MapContainer.RequestTrackEntity += (ent, trackEntity) =>
        {
            RequestTrackEntity?.Invoke(ent, trackEntity);
        };
        // End Frontier

        // Lua start: StarMap
        StarMapContainer.RequestWarpToStar += star =>
        { OnWarpToStarRequest?.Invoke(star); };
        // Lua end: StarMap

        DockContainer.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };

        DockContainer.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        DockContainer.UndockAllRequest += dockEntities =>
        {
            UndockAllRequest?.Invoke(dockEntities);
        };

        DockContainer.ToggleFTLLockRequest += (dockEntities, enabled) =>
        {
            ToggleFTLLockRequest?.Invoke(dockEntities, enabled);
        };

        // Lua
        NavContainer.OnWeaponSelectionChanged += () => OnWeaponSelectionChanged?.Invoke();
        NavContainer.OnFireControlRefresh += () => OnFireControlRefresh?.Invoke();
        ExpContainer.OnClaim += (index, seed) => OnClaimExpedition?.Invoke(index, seed);
        ExpContainer.OnConfirm += () => OnConfirmExpedition?.Invoke();
        ExpContainer.OnCancel += () => OnCancelExpedition?.Invoke();
        ExpContainer.OnFinish += () => OnFinishExpedition?.Invoke();
        // End Lua

        NfInitialize(); // Frontier Initialization for the ShuttleConsoleWindow
    }

    private void ClearModes(ShuttleConsoleMode mode)
    {
        if (mode != ShuttleConsoleMode.Nav)
        {
            NavContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Map)
        {
            MapContainer.Visible = false;
            MapContainer.SetMap(MapId.Nullspace, Vector2.Zero);
        }

        if (mode != ShuttleConsoleMode.StarMap)
        { StarMapContainer.Visible = false; }

        if (mode != ShuttleConsoleMode.Dock)
        {
            DockContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Exp)
        {
            ExpContainer.SetTabActive(false);
            ExpContainer.Visible = false;
        }
    }

    private void NavPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Nav);
    }

    private void MapPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Map);
    }

    private void StarMapPressed(BaseButton.ButtonEventArgs obj)
    { SwitchMode(ShuttleConsoleMode.StarMap); }

    private void DockPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Dock);
    }

    private void ExpPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Exp);
    }

    private void SetupMode(ShuttleConsoleMode mode)
    {
        switch (mode)
        {
            case ShuttleConsoleMode.Nav:
                NavContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Map:
                MapContainer.Visible = true;
                MapContainer.Startup();
                break;
            case ShuttleConsoleMode.StarMap:
                StarMapContainer.Visible = true;
                StarMapContainer.Startup();
                break;
            case ShuttleConsoleMode.Dock:
                DockContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Exp:
                ExpContainer.Visible = true;
                ExpContainer.SetTabActive(true);
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void SwitchMode(ShuttleConsoleMode mode)
    {
        if (_mode == mode)
            return;

        var wasStarMap = _mode == ShuttleConsoleMode.StarMap;
        var wasMap = _mode == ShuttleConsoleMode.Map;
        var wasExp = _mode == ShuttleConsoleMode.Exp;
        _mode = mode;
        ClearModes(mode);
        SetupMode(_mode);
        var isStarMap = _mode == ShuttleConsoleMode.StarMap;
        var isMap = _mode == ShuttleConsoleMode.Map;
        var isExp = _mode == ShuttleConsoleMode.Exp;
        if (wasStarMap != isStarMap) OnStarMapVisibilityChanged?.Invoke(isStarMap);
        if (wasMap != isMap) OnMapVisibilityChanged?.Invoke(isMap);
        if (wasExp != isExp) OnExpVisibilityChanged?.Invoke(isExp);
    }

    public enum ShuttleConsoleMode : byte
    {
        Nav,
        Map,
        StarMap,
        Dock,
        Exp,
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        NavContainer.SetShuttle(coordinates?.EntityId);
        NavContainer.SetConsole(owner);
        MapContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetConsole(owner);
        StarMapContainer.SetShuttle(coordinates?.EntityId);
        StarMapContainer.SetConsole(owner);

        NavContainer.UpdateState(cState.NavState);
        NavContainer.UpdateWeapons(cState.FireControlConnected, cState.FireControllables); // Lua
        MapContainer.UpdateState(cState.MapState);
        StarMapContainer.UpdateState(cState.StarMapState);
        DockContainer.UpdateState(coordinates?.EntityId, cState.DockState);
        ExpContainer.UpdateState(cState.ExpeditionState);
        UpdateExpeditionLock(cState.ExpeditionState);
    }

    private void UpdateExpeditionLock(ExpeditionConsoleState? expState)
    {
        if (expState == null)
        {
            ExpModeButton.Disabled = true;
            ExpModeButton.ToolTip = null;
            return;
        }

        var disabled = expState.InCombat || !expState.MassAllowed || !expState.Enabled;
        ExpModeButton.Disabled = disabled;

        string? tooltip = null;
        if (expState.InCombat)
            tooltip = Loc.GetString("expedition-combat-block");
        else if (!expState.MassAllowed)
            tooltip = Loc.GetString("expedition-mass-block", ("mass", expState.CurrentMass), ("limit", expState.MassLimit));
        else if (!expState.Enabled)
            tooltip = Loc.GetString("expedition-disabled");
        else if (!string.IsNullOrEmpty(expState.BlockReason))
            tooltip = expState.BlockReason;

        ExpModeButton.ToolTip = tooltip;
        if (disabled && _mode == ShuttleConsoleMode.Exp) SwitchMode(ShuttleConsoleMode.Nav);
    }
}
