using System.Linq;
using Content.Client._NF.LateJoin.Interfaces;
using Content.Client._NF.LateJoin.ListItems;
using Content.Client.Lobby;
using Content.Client.Players.PlayTimeTracking;
using Content.Shared.GameTicking;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NF.LateJoin.Controls;

[GenerateTypedNameReferences]
public sealed partial class StationPickerControl : PickerControl
{
    [Dependency] private readonly ILocalizationManager _loc = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly JobRequirementsManager _jobReqs = default!;
    [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
    private readonly SpriteSystem _spriteSystem;

    public StationPickerControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entitySystem.GetEntitySystem<SpriteSystem>();
    }

    private Dictionary<NetEntity, StationJobInformation> _lobbyJobs = new();
    private StationListItem.ViewState? _lastSelectedStation;
    public Action<NetEntity, string>? OnJobJoined;

    public override void UpdateUi(IReadOnlyDictionary<NetEntity, StationJobInformation> obj)
    {
        _lobbyJobs = new Dictionary<NetEntity, StationJobInformation>(obj);
        StationItemList.RemoveAllChildren();

        var stationViewStates = BuildStationViewStateList(_lobbyJobs);
        foreach (var stationViewState in stationViewStates)
        {
            var item = new StationListItem(stationViewState);
            item.StationButton.OnPressed += _ => OnStationPressed(stationViewState);
            StationItemList.AddChild(item);
        }
        StationJobItemList.RemoveAllChildren();
        NoJobsMessage.Visible = false;
        if (_lastSelectedStation != null && obj.TryGetValue(_lastSelectedStation.StationEntity, out var stationInfo))
        {
            foreach (var jobViewState in BuildJobViewStateList(stationInfo))
            {
                var item = new JobListItem(jobViewState);
                item.OnPressed += _ =>
                {
                    OnJobJoined?.Invoke(_lastSelectedStation.StationEntity, jobViewState.JobId);
                };
                StationJobItemList.AddChild(item);
            }

            NoJobsMessage.Visible = HasNoOpenJobs(stationInfo);
        }

        StationName.Text = _lastSelectedStation?.StationName ?? "";
        StationDescription.Text = _lastSelectedStation?.StationDescription ?? "";
    }

    private void OnStationPressed(StationListItem.ViewState stationItemViewState)
    {
        _lastSelectedStation = stationItemViewState;
        UpdateUi(_lobbyJobs);
    }

    private List<JobListItem.ViewState> BuildJobViewStateList(StationJobInformation jobInformation)
    {
        var viewStateList = new List<JobListItem.ViewState>();

        foreach (var (jobPrototype, jobCount) in jobInformation.JobsAvailable)
        {
            if (_preferencesManager.Preferences?.SelectedCharacter is not HumanoidCharacterProfile profile)
            {
                continue;
            }

            var prototype = _prototypeManager.Index(jobPrototype);
            var jobName = prototype.LocalizedName + jobCount.WrapJobCountInParentheses();
            Texture? texture = null;

            if (_prototypeManager.TryIndex(prototype.Icon, out var jobIcon))
            {
                texture = _spriteSystem.Frame0(jobIcon.Icon);
            }

            var buttonTooltip = "";
            if (!_jobReqs.IsAllowed(prototype, profile, out var denyReason))
            {
                buttonTooltip = denyReason.ToString();
            }

            var isButtonDisabled = jobCount == 0 || !_jobReqs.IsAllowed(prototype, profile, out _);
            var viewState = new JobListItem.ViewState(
                jobId: jobPrototype,
                jobName: jobName,
                toolTip: buttonTooltip,
                disabled: isButtonDisabled,
                jobIcon: texture
            );
            viewStateList.Add(viewState);
        }

        return viewStateList;
    }
    private List<StationListItem.ViewState> BuildStationViewStateList(
        IReadOnlyDictionary<NetEntity, StationJobInformation> obj)
    {
        var stationList = obj
            .Where(kvp => kvp.Value.IsLateJoinStation)
            .Where(kvp => ShouldShowStation(kvp.Value))
            .ToDictionary(kvp => kvp.Key, kvp => kvp.Value);
        var viewStateList = new List<StationListItem.ViewState>();

        foreach (var (stationEntity, stationJobInformation) in stationList)
        {
            var viewState = new StationListItem.ViewState(
                stationEntity,
                stationJobInformation.GetStationNameWithJobCount(),
                stationJobInformation.StationDisplayInfo?.StationSubtext != null
                    ? _loc.GetString(stationJobInformation.StationDisplayInfo.StationSubtext)
                    : "",
                stationJobInformation.StationDisplayInfo?.StationDescription != null
                    ? _loc.GetString(stationJobInformation.StationDisplayInfo.StationDescription)
                    : "",
                _lastSelectedStation?.StationEntity == stationEntity,
                stationJobInformation.StationDisplayInfo?.StationIcon?.CanonPath
            );

            viewStateList.Add(viewState);
        }
        var sorted = viewStateList
            .OrderBy(viewState => (obj[viewState.StationEntity].StationDisplayInfo?.LobbySortOrder ?? 0) == 0
                ? int.MaxValue
                : obj[viewState.StationEntity].StationDisplayInfo!.LobbySortOrder)
            .ToList();

        if (_lastSelectedStation != null && sorted.All(viewState => viewState.StationEntity != _lastSelectedStation.StationEntity))
            _lastSelectedStation = null;

        if (_lastSelectedStation == null)
        {
            if (sorted.Count == 0)
                return sorted;

            _lastSelectedStation = sorted[0];
            sorted[0].Selected = true;
            return sorted;
        }

        foreach (var viewState in sorted)
        {
            viewState.Selected = viewState.StationEntity == _lastSelectedStation.StationEntity;
        }

        return sorted;
    }

    private bool ShouldShowStation(StationJobInformation jobInformation)
    {
        if (_preferencesManager.Preferences?.SelectedCharacter is not HumanoidCharacterProfile profile)
            return jobInformation.JobsAvailable.Any(job => job.Value != 0);

        var requiredCompany = jobInformation.StationDisplayInfo?.RequiredCompany;
        if (!string.IsNullOrWhiteSpace(requiredCompany) &&
            !MatchesRequiredCompany(profile.Company, requiredCompany))
        {
            return false;
        }

        if (HasNoOpenJobs(jobInformation))
            return true;

        foreach (var (jobPrototype, jobCount) in jobInformation.JobsAvailable)
        {
            if (jobCount == 0)
                continue;

            var prototype = _prototypeManager.Index(jobPrototype);
            if (_jobReqs.IsAllowed(prototype, profile, ignoreTimedRequirements: true, out _))
                return true;
        }

        return false;
    }

    private static bool HasNoOpenJobs(StationJobInformation jobInformation)
    {
        return jobInformation.JobsAvailable.Count > 0 && jobInformation.JobsAvailable.All(job => job.Value == 0);
    }

    private static bool MatchesRequiredCompany(string? profileCompany, string requiredCompany)
    {
        var currentCompany = profileCompany ?? "None";

        foreach (var company in requiredCompany.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (string.Equals(currentCompany, company, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }
}
