// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaWorld Contributors
// See AGPLv3.txt for details.

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Lua.Disease.Components;
using Content.Shared._Lua.Disease.UI;

namespace Content.Client._Lua.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class DiseaseAnalyzerWindow : FancyWindow
{
    public Action? Analyze;
    public Action? PrintReport;
    public Action? Contain;
    public Action? ClearSample;

    public DiseaseAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);

        AnalyzeButton.OnPressed += _ => Analyze?.Invoke();
        PrintReportButton.OnPressed += _ => PrintReport?.Invoke();
        ContainButton.OnPressed += _ => Contain?.Invoke();
        ClearButton.OnPressed += _ => ClearSample?.Invoke();
    }

    public void UpdateUI(DiseaseAnalyzerWindowInterfaceState state)
    {
        var status = state.Status;
        var progress = state.Progress;
        var diseaseNames = state.DiseaseNames;
        var code = state.Code;
        var fragile = state.Fragile;
        var filled = state.Filled;

        UpdateStatus(status, filled);
        UpdateSubstanceCode(code);
        UpdateProgress(progress, status);
        UpdateButtons(status, filled, fragile);
        UpdateDiseaseInfo(filled, status, diseaseNames);
    }

    private void UpdateSubstanceCode(string code)
    {
        SubstanceCodeLabel.Text = code;
    }

    private void UpdateProgress(float progress, DiseaseAnalyzerStatus status)
    {
        ProgressBar.Value = status == DiseaseAnalyzerStatus.Analyzed ? 100f : progress * 100;
    }

    private void UpdateStatus(DiseaseAnalyzerStatus status, bool filled)
    {
        if (!filled && status != DiseaseAnalyzerStatus.Analyzed)
        {
            StatusLabel.Text = Loc.GetString("disease-analyzer-status-label-not-filled");
            StatusLabel.FontColorOverride = Color.DarkGray;
            return;
        }

        StatusLabel.Text = status switch
        {
            DiseaseAnalyzerStatus.NotAnalyzed => Loc.GetString("disease-analyzer-status-label-not-analyzed"),
            DiseaseAnalyzerStatus.Analyzing => Loc.GetString("disease-analyzer-status-label-analyzing"),
            DiseaseAnalyzerStatus.Analyzed => Loc.GetString("disease-analyzer-status-label-analyzed"),
            _ => Loc.GetString("disease-analyzer-status-label-not-filled")
        };

        StatusLabel.FontColorOverride = status switch
        {
            DiseaseAnalyzerStatus.NotAnalyzed => Color.Gray,
            DiseaseAnalyzerStatus.Analyzing => Color.Yellow,
            DiseaseAnalyzerStatus.Analyzed => Color.Green,
            _ => Color.DarkGray
        };
    }

    private void UpdateButtons(DiseaseAnalyzerStatus status, bool filled, bool fragile)
    {
        var isNotAnalyzed = status == DiseaseAnalyzerStatus.NotAnalyzed;
        var isAnalyzing = status == DiseaseAnalyzerStatus.Analyzing;
        var isAnalyzed = status == DiseaseAnalyzerStatus.Analyzed;

        if (!filled && !isAnalyzed)
        {
            SetAllButtonsDisabled(true);
            return;
        }

        AnalyzeButton.Disabled = !isNotAnalyzed;
        PrintReportButton.Disabled = !isAnalyzed;
        ClearButton.Disabled = isAnalyzing;
        ContainButton.Disabled = !fragile || isAnalyzing;
    }

    private void UpdateDiseaseInfo(bool filled, DiseaseAnalyzerStatus status, List<string> diseaseNames)
    {
        DiseaseBox.RemoveAllChildren();

        if (!filled)
        {
            DiseaseInfo.Visible = false;
            return;
        }

        if (status != DiseaseAnalyzerStatus.Analyzed)
        {
            return;
        }

        DiseaseInfo.Visible = true;

        if (diseaseNames.Count == 0)
        {
            DiseaseFoundLabel.Text = Loc.GetString("disease-analyzer-no-diseases");
            return;
        }

        DiseaseFoundLabel.Text = Loc.GetString("disease-analyzer-diseases");

        foreach (var diseaseName in diseaseNames)
        {
            DiseaseBox.AddChild(new Label
            {
                Text = $"- {Loc.GetString(diseaseName)}",
            });
        }
    }

    private void SetAllButtonsDisabled(bool state)
    {
        AnalyzeButton.Disabled = state;
        PrintReportButton.Disabled = state;
        ContainButton.Disabled = state;
        ClearButton.Disabled = state;
    }
}
