using Content.Shared.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ReputationActionsWindow : DefaultWindow
{
    private PlayerInfo? _selectedPlayer;

    public ReputationActionsWindow()
    {
        RobustXamlLoader.Load(this);
        PlayerList.OnSelectionChanged += OnSelectionChanged;
        SubmitPlayerReputationButton.OnPressed += _ => OpenReputationPanel("player");
        SubmitAdminReputationButton.OnPressed += _ => OpenReputationPanel("admin");
    }

    private void OnSelectionChanged(PlayerInfo? player)
    {
        _selectedPlayer = player;
        var disabled = _selectedPlayer == null;
        SubmitPlayerReputationButton.Disabled = disabled;
        SubmitAdminReputationButton.Disabled = disabled;
    }

    private void OpenReputationPanel(string kind)
    {
        if (_selectedPlayer == null) return;
        IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"reputationpanel {kind} \"{_selectedPlayer.SessionId}\"");
    }
}
