using Content.Shared.Administration;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkPanel : BoxContainer
    {
        private readonly Action<string> _messageSender;
        private readonly Action _closeConversation;
        private readonly Action _reopenConversation;
        private readonly Action<ReputationVoteValue, string?> _adminRatingSender;
        private readonly bool _isAdminPanel;
        public int Unread { get; private set; } = 0;
        public DateTime LastMessage { get; private set; } = DateTime.MinValue;
        private List<string> PeopleTyping { get; set; } = new();
        public event Action<string>? InputTextChanged;

        public BwoinkPanel(
            Action<string> messageSender,
            Action closeConversation,
            Action reopenConversation,
            Action<ReputationVoteValue, string?> adminRatingSender,
            bool isAdminPanel)
        {
            RobustXamlLoader.Load(this);
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            msg.AddText(Loc.GetString("bwoink-system-messages-being-relayed-to-discord"));
            msg.Pop();
            RelayedToDiscordLabel.SetMessage(msg);
            _messageSender = messageSender;
            _closeConversation = closeConversation;
            _reopenConversation = reopenConversation;
            _adminRatingSender = adminRatingSender;
            _isAdminPanel = isAdminPanel;
            OnVisibilityChanged += c =>
            { if (c.Visible) Unread = 0; };
            SenderLineEdit.OnTextEntered += Input_OnTextEntered;
            SenderLineEdit.OnTextChanged += Input_OnTextChanged;
            RatingComment.OnTextChanged += _ => UpdateRatingButtons();
            CloseConversation.OnPressed += _ => _closeConversation.Invoke();
            ReopenConversation.OnPressed += _ => _reopenConversation.Invoke();
            RatePositive.OnPressed += _ => SendRating(ReputationVoteValue.Like);
            RateNegative.OnPressed += _ => SendRating(ReputationVoteValue.Dislike);
            RatingComment.Placeholder = new Rope.Leaf(Loc.GetString("bwoink-conversation-rating-comment-placeholder", ("min", ReputationConstants.MinNegativeCommentLength)));
            UpdateTypingIndicator();
            UpdateConversationState(false, false, false, null);
        }

        private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (string.IsNullOrWhiteSpace(args.Text)) return;
            _messageSender.Invoke(args.Text);
            SenderLineEdit.Clear();
        }

        private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
        { InputTextChanged?.Invoke(args.Text); }

        public void ReceiveLine(SharedBwoinkSystem.BwoinkTextMessage message)
        {
            if (!Visible) Unread++;
            var formatted = new FormattedMessage(1);
            formatted.AddMarkupOrThrow($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {message.Text}");
            TextOutput.AddMessage(formatted);
            LastMessage = message.SentAt;
        }

        public void UpdateConversationState(bool closed, bool canRate, bool ratingSubmitted, string? adminName)
        {
            SenderLineEdit.Editable = true;
            CloseConversation.Disabled = closed;
            RatingComment.Visible = canRate;
            RatePositive.Visible = canRate;
            RateNegative.Visible = canRate;
            ReopenConversation.Visible = !_isAdminPanel && closed && ratingSubmitted;
            var status = new FormattedMessage();
            status.PushColor(closed ? Color.LightGray : Color.LightGreen);
            status.AddText(GetConversationStatusText(closed, canRate, ratingSubmitted, adminName));
            status.Pop();
            ConversationStatus.SetMessage(status);
            UpdateRatingButtons();
        }

        private string GetConversationStatusText(bool closed, bool canRate, bool ratingSubmitted, string? adminName)
        {
            if (ratingSubmitted) return Loc.GetString("bwoink-conversation-rating-submitted");
            if (canRate && !string.IsNullOrWhiteSpace(adminName)) return Loc.GetString("bwoink-conversation-can-rate", ("admin", adminName));
            if (closed) return Loc.GetString(_isAdminPanel ? "bwoink-conversation-closed-admin" : "bwoink-conversation-closed-user");
            return Loc.GetString(_isAdminPanel ? "bwoink-conversation-open-admin" : "bwoink-conversation-open-user");
        }

        private void SendRating(ReputationVoteValue value)
        {
            var comment = Rope.Collapse(RatingComment.TextRope).Trim();
            _adminRatingSender.Invoke(value, string.IsNullOrWhiteSpace(comment) ? null : comment);
        }

        private void UpdateRatingButtons()
        {
            if (!RateNegative.Visible) return;
            var commentLength = Rope.Collapse(RatingComment.TextRope).Trim().Length;
            RateNegative.Disabled = commentLength < ReputationConstants.MinNegativeCommentLength;
            RatePositive.Disabled = commentLength > ReputationConstants.MaxCommentLength;
        }

        private void UpdateTypingIndicator()
        {
            var msg = new FormattedMessage();
            msg.PushColor(Color.LightGray);
            var text = PeopleTyping.Count == 0 ? string.Empty : Loc.GetString("bwoink-system-typing-indicator", ("players", string.Join(", ", PeopleTyping)), ("count", PeopleTyping.Count));
            msg.AddText(text);
            msg.Pop();
            TypingIndicator.SetMessage(msg);
        }

        public void UpdatePlayerTyping(string name, bool typing)
        {
            if (typing)
            {
                if (PeopleTyping.Contains(name)) return;
                PeopleTyping.Add(name);
                Timer.Spawn(TimeSpan.FromSeconds(10), () =>
                {
                    if (Disposed) return;
                    PeopleTyping.Remove(name);
                    UpdateTypingIndicator();
                });
            }
            else { PeopleTyping.Remove(name); }
            UpdateTypingIndicator();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
            InputTextChanged = null;
        }
    }
}
