- type: latheRecipe
  id: CSInteQShieldBelt
  result: CSClothingBeltInteQShieldBelt
  categories:
  - Clothing
  completetime: 15
  materials:
    Plastic: 500
    Silver: 200
    Gold: 100
    Durathread: 200