name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    if: ${{ github.event.review.state == 'APPROVED' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add label if founder
        if: ${{ github.actor == 'HacksLua' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "APPROVED"
