name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        if: ${{ github.actor == 'HacksLua' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: APPROVED
          github_token: ${{ secrets.LABELER_PAT }}
          repo: ${{ github.repository }}

